spring:
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/BikeRental
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update